In [ ]:
import numpy as np
import math
import pandas as pd

1. Create a row and column vector using input method and manually

In [ ]:
# Using Input Method
input_row = input("Enter values for the row vector (space-separated): ")
row_vector = np.array([float(x) for x in input_row.split()]) #delimetr used is space

input_col = input("Enter values for the column vector (space-separated): ")
col_vector = np.array([float(x) for x in input_col.split()]).reshape(-1, 1) #delimetr used is space, reshape is based on no. of col only (here 1).

print("Row Vector (Input):")
print(row_vector)

print("Column Vector (Input):")
print(col_vector)


Enter values for the row vector (space-separated): 1 5 8 6
Enter values for the column vector (space-separated): 7 8 9 2 5
Row Vector (Input):
[1. 5. 8. 6.]
Column Vector (Input):
[[7.]
 [8.]
 [9.]
 [2.]
 [5.]]


In [ ]:
# Using Manual Method
manual_row = [2, 5, 8]
manual_col = [4, 5, 6, 7]

row_vector_manual = np.array(manual_row)
col_vector_manual = np.array(manual_col).reshape(-1, 1)

print("Row Vector (Manual):")
print(row_vector_manual)

print("Column Vector (Manual):")
print(col_vector_manual)

Row Vector (Manual):
[2 5 8]
Column Vector (Manual):
[[4]
 [5]
 [6]
 [7]]


2.  Create a matrix (5 × 5) using the input method as well as manually and save it as “a”

In [ ]:
# Using Input Method
input_matrix = []
print("Enter values for the 5x5 matrix (row by row):")
for _ in range(5):
    row = input("Enter values for the current row (space-separated): ")
    row_values = [float(x) for x in row.split()]
    input_matrix.append(row_values)

a_input = np.array(input_matrix)

print("Matrix 'a' (Input):") #25 23 21 24 22  19 18 20 16 17  11 15 12 14 13  8 6 7 10 9  3 5 2 1 4
print(a_input)

Enter values for the 5x5 matrix (row by row):
Enter values for the current row (space-separated): 25 23 21 24 22
Enter values for the current row (space-separated): 19 18 20 16 17
Enter values for the current row (space-separated): 11 15 12 14 13
Enter values for the current row (space-separated): 8 6 7 10 9
Enter values for the current row (space-separated): 3 5 2 1 4
Matrix 'a' (Input):
[[25. 23. 21. 24. 22.]
 [19. 18. 20. 16. 17.]
 [11. 15. 12. 14. 13.]
 [ 8.  6.  7. 10.  9.]
 [ 3.  5.  2.  1.  4.]]


In [ ]:
# Using Manual Method
manual_matrix = np.array([
    [25, 20, 23, 22, 24],
    [21, 19, 15, 16, 18],
    [14, 17, 13, 11, 12],
    [6, 10, 8, 9, 7],
    [4, 2, 3, 5, 1]
])

a_manual = manual_matrix

print("Matrix 'a' created using the Manual Method:")
print(a_manual)

Matrix 'a' created using the Manual Method:
[[25 20 23 22 24]
 [21 19 15 16 18]
 [14 17 13 11 12]
 [ 6 10  8  9  7]
 [ 4  2  3  5  1]]


In [ ]:
#since both ibput and manual method have same matrix, assigning both as 'a'
a = a_input
a

array([[25., 23., 21., 24., 22.],
       [19., 18., 20., 16., 17.],
       [11., 15., 12., 14., 13.],
       [ 8.,  6.,  7., 10.,  9.],
       [ 3.,  5.,  2.,  1.,  4.]])

3. Get 3rd row out of the matrix.


In [ ]:
third_row = a[2,:]
third_row

array([11., 15., 12., 14., 13.])

4. Get 4th column out of the matrix

In [ ]:
fourth_col = a[:,3]
fourth_col

array([24., 16., 14., 10.,  1.])

5.  Sort matrix row wise and column wise.

In [ ]:
a_row_sort = np.sort(a, axis=1)
a_row_sort

array([[21., 22., 23., 24., 25.],
       [16., 17., 18., 19., 20.],
       [11., 12., 13., 14., 15.],
       [ 6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.]])

In [ ]:
a_col_sort = np.sort(a, axis=0)
a_col_sort

array([[ 3.,  5.,  2.,  1.,  4.],
       [ 8.,  6.,  7., 10.,  9.],
       [11., 15., 12., 14., 13.],
       [19., 18., 20., 16., 17.],
       [25., 23., 21., 24., 22.]])

6. Apply for loop in matrix, if element is greater than 2, multiply element by 10 say it as “b”.

In [ ]:
# Creating new matrix 'b'
b = np.copy(a)  # Create a copy of 'a' to modify
for row in range(b.shape[0]): #iterate over rows
    for col in range(b.shape[1]): #iterate over columns
        if b[row, col] > 2:
            b[row, col] *= 10

print("Matrix 'a':")
print(a)

print("Matrix 'b' after applying condition:")
print(b)

Matrix 'a':
[[25. 23. 21. 24. 22.]
 [19. 18. 20. 16. 17.]
 [11. 15. 12. 14. 13.]
 [ 8.  6.  7. 10.  9.]
 [ 3.  5.  2.  1.  4.]]
Matrix 'b' after applying condition:
[[250. 230. 210. 240. 220.]
 [190. 180. 200. 160. 170.]
 [110. 150. 120. 140. 130.]
 [ 80.  60.  70. 100.  90.]
 [ 30.  50.   2.   1.  40.]]


7. Add matrix a and b.

In [ ]:
sum= a+b
sum

array([[275., 253., 231., 264., 242.],
       [209., 198., 220., 176., 187.],
       [121., 165., 132., 154., 143.],
       [ 88.,  66.,  77., 110.,  99.],
       [ 33.,  55.,   4.,   2.,  44.]])

8. Subtract matrix b from

In [ ]:
subtract = a-b
subtract

array([[-225., -207., -189., -216., -198.],
       [-171., -162., -180., -144., -153.],
       [ -99., -135., -108., -126., -117.],
       [ -72.,  -54.,  -63.,  -90.,  -81.],
       [ -27.,  -45.,    0.,    0.,  -36.]])

9. Multiply matrix a by b element wise and matrix multiplication.

In [ ]:
#element wise multiplication
c = a*b
c

array([[6.25e+03, 5.29e+03, 4.41e+03, 5.76e+03, 4.84e+03],
       [3.61e+03, 3.24e+03, 4.00e+03, 2.56e+03, 2.89e+03],
       [1.21e+03, 2.25e+03, 1.44e+03, 1.96e+03, 1.69e+03],
       [6.40e+02, 3.60e+02, 4.90e+02, 1.00e+03, 8.10e+02],
       [9.00e+01, 2.50e+02, 4.00e+00, 1.00e+00, 1.60e+02]])

In [ ]:
#matrix multiplication
d= np.dot(a,b)
d

array([[15510., 15580., 14094., 15042., 15180.],
       [12160., 12420., 11144., 11857., 11960.],
       [ 8430.,  8520.,  7756.,  8133.,  8310.],
       [ 4980.,  5020.,  4438.,  4869.,  4950.],
       [ 2120.,  2150.,  1948.,  1904.,  2020.]])

10. Divide each element of matrix a and b by 18.

In [ ]:
#matrix a
div_a = a/18
print(div_a)

[[1.38888889 1.27777778 1.16666667 1.33333333 1.22222222]
 [1.05555556 1.         1.11111111 0.88888889 0.94444444]
 [0.61111111 0.83333333 0.66666667 0.77777778 0.72222222]
 [0.44444444 0.33333333 0.38888889 0.55555556 0.5       ]
 [0.16666667 0.27777778 0.11111111 0.05555556 0.22222222]]


In [ ]:
#matrix b
div_b = b/18
print(div_b)

[[13.88888889 12.77777778 11.66666667 13.33333333 12.22222222]
 [10.55555556 10.         11.11111111  8.88888889  9.44444444]
 [ 6.11111111  8.33333333  6.66666667  7.77777778  7.22222222]
 [ 4.44444444  3.33333333  3.88888889  5.55555556  5.        ]
 [ 1.66666667  2.77777778  0.11111111  0.05555556  2.22222222]]


11. find the inverse, rank, condition number, singular value decomposition and the norm of matrices a and b

In [ ]:
matrix_choice = input("Choose matrix (a or b): ")

if matrix_choice == 'a':
    matrix = a
elif matrix_choice == 'b':
    matrix = b
else:
    print("Invalid choice. Please choose 'a' or 'b'.")

if 'matrix' in locals():
    print("Selected Matrix:")
    print(matrix)

Choose matrix (a or b): b
Selected Matrix:
[[250. 230. 210. 240. 220.]
 [190. 180. 200. 160. 170.]
 [110. 150. 120. 140. 130.]
 [ 80.  60.  70. 100.  90.]
 [ 30.  50.   2.   1.  40.]]


In [ ]:
# matrix = a
#inverse of matrix
def find_inverse(matrix):
    n = matrix.shape[0]
    augmented_matrix = np.hstack((matrix, np.eye(n))) #A*I

    for i in range(n):
        pivot = augmented_matrix[i, i] #diagonal elements
        augmented_matrix[i] = augmented_matrix[i] / pivot

        for j in range(n):
            if j != i:
                factor = augmented_matrix[j, i] #non-diagonal elements
                augmented_matrix[j] -= factor * augmented_matrix[i]

    inverse_matrix = augmented_matrix[:, n:]
    return inverse_matrix


# Rank of a matrix
rank = np.linalg.matrix_rank(matrix)


#Condition number of matrix
def matrix_condition_number(matrix):
    try:
        matrix_norm = np.linalg.norm(matrix, ord=2)
        inverse_matrix = np.linalg.inv(matrix)
        inverse_matrix_norm = np.linalg.norm(inverse_matrix, ord=2)
        condition_number = matrix_norm * inverse_matrix_norm
        return condition_number
    except np.linalg.LinAlgError:
        return np.inf  # If the matrix is singular, condition number is infinite

condition_number = matrix_condition_number(matrix)


# singular value decomposition of a matrix
U, Sigma, VT = np.linalg.svd(matrix) #A=U*SIgma*VT


#2_Norm of a matrix
def calculate_2_norm(matrix):
    sum_of_squares = np.sum(matrix ** 2)
    norm_2 = np.sqrt(sum_of_squares)
    return norm_2
two_norm = calculate_2_norm(matrix)


In [ ]:
#matrix a
# matrix = a
a_inverse = find_inverse(matrix)
print('original matrix of a')
print(a)
print('inverse matrix of a')
print(a_inverse)

print("Rank of the matrix:", rank)

print("Condition Number:", condition_number)

print('singular value decomposition of matrix')
print("Matrix U (Left Singular Vectors):")
print(U)
print("Matrix Sigma (Singular Values):")
print(np.diag(Sigma))
print("Matrix VT (Transpose of Right Singular Vectors):")
print(VT)

print("2-Norm of the matrix:", two_norm)

original matrix of a
[[25. 23. 21. 24. 22.]
 [19. 18. 20. 16. 17.]
 [11. 15. 12. 14. 13.]
 [ 8.  6.  7. 10.  9.]
 [ 3.  5.  2.  1.  4.]]
inverse matrix of a
[[ 0.19472789 -0.04217687 -0.22636054 -0.08690476  0.03945578]
 [ 0.06632653 -0.06938776  0.13163265 -0.23571429  0.03265306]
 [-0.1505102   0.19591837  0.04744898 -0.00357143 -0.15102041]
 [ 0.06207483 -0.10340136  0.11037415 -0.01547619 -0.22585034]
 [-0.16921769  0.0462585  -0.04608844  0.36547619  0.31156463]]
Rank of the matrix: 5
Condition Number: 43.575255052554425
singular value decomposition of matrix
Matrix U (Left Singular Vectors):
[[-0.69562631 -0.26396977 -0.08653226  0.55097882 -0.367911  ]
 [-0.54349699  0.61294289 -0.42541189 -0.34259553  0.17482867]
 [-0.39260572 -0.08939009  0.73321033 -0.5259766  -0.15369252]
 [-0.24155995 -0.6230702  -0.17104769 -0.15865443  0.706402  ]
 [-0.09068953  0.39801247  0.49465362  0.52652448  0.55807819]]
Matrix Sigma (Singular Values):
[[74.01705862  0.          0.          0.      

In [ ]:
#matrix b
# matrix = b
b_inverse = find_inverse(matrix)
print('original matrix of b')
print(b)
print('inverse matrix of b')
print(b_inverse)

print("Rank of the matrix:", rank)

print("Condition Number:", condition_number)

print('singular value decomposition of matrix')
print("Matrix U (Left Singular Vectors):")
print(U)
print("Matrix Sigma (Singular Values):")
print(np.diag(Sigma))
print("Matrix VT (Transpose of Right Singular Vectors):")
print(VT)

print("2-Norm of the matrix:", two_norm)

original matrix of b
[[250. 230. 210. 240. 220.]
 [190. 180. 200. 160. 170.]
 [110. 150. 120. 140. 130.]
 [ 80.  60.  70. 100.  90.]
 [ 30.  50.   2.   1.  40.]]
inverse matrix of b
[[ 0.01889757 -0.00352334 -0.0221419  -0.00874493  0.00267478]
 [ 0.00615661 -0.00636414  0.01357222 -0.02361649  0.00221361]
 [-0.01284934  0.01693414  0.00285349 -0.00014873 -0.01023796]
 [ 0.00950009 -0.0143147   0.00820882 -0.00123593 -0.01531083]
 [-0.02146398  0.01010884 -0.00070674  0.03611764  0.02112156]]
Rank of the matrix: 5
Condition Number: 43.575255052554425
singular value decomposition of matrix
Matrix U (Left Singular Vectors):
[[-0.69562631 -0.26396977 -0.08653226  0.55097882 -0.367911  ]
 [-0.54349699  0.61294289 -0.42541189 -0.34259553  0.17482867]
 [-0.39260572 -0.08939009  0.73321033 -0.5259766  -0.15369252]
 [-0.24155995 -0.6230702  -0.17104769 -0.15865443  0.706402  ]
 [-0.09068953  0.39801247  0.49465362  0.52652448  0.55807819]]
Matrix Sigma (Singular Values):
[[74.01705862  0.     

12. find the norm, inner product and outer product of column vector.

In [ ]:
# Column vector
col_vect1 = np.array([[1],[2],[3]])

# Calculate the norm of the column vector
norm = np.linalg.norm(col_vect1)
print("Norm of the column vector:", norm)

# Another column vector for inner product
col_vect2 = np.array([[4],[5],[6]])

# Calculate the inner product of the two column vectors
inner_product = np.dot(col_vect1.T, col_vect2)
print("Inner product of the column vectors:", inner_product)

# Calculate the outer product of the two column vectors
outer_product = np.outer(col_vect1, col_vect2.T)
print("Outer product of the column vectors:")
print(outer_product)


Norm of the column vector: 3.7416573867739413
Inner product of the column vectors: [[32]]
Outer product of the column vectors:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


Write a function called derivative which takes input parameters f(x), a, method (forward,backwardand central) and h(step size) (with default values method ‘central’ and h = 0.01) and returns the corresponding difference formula for derivative of function at a with step size h and then test your function on e^x and cos x at x = 0.5.

In [ ]:
def derivative(f, a, method='central', h=0.01):
    if method == 'forward':
        return (f(a + h) - f(a)) / h
    elif method == 'backward':
        return (f(a) - f(a - h)) / h
    elif method == 'central':
        return (f(a + h) - f(a - h)) / (2 * h)
    else:
        raise ValueError("Invalid differentiation method. Choose 'forward', 'backward', or 'central'.")

In [ ]:
# Test function and point
def test_function(x):
    return math.exp(x)  # Test with e^x

x = 0.5  # Point to evaluate the derivative

# Test the function using different methods
for method in ['forward', 'backward', 'central']:
    derivative_value = derivative(test_function, x, method=method)
    print(f"Derivative using {method} method:", derivative_value)

Derivative using forward method: 1.6569924245758205
Derivative using backward method: 1.6405050744749294
Derivative using central method: 1.648748749525375


In [ ]:
# Test function and point
def test_function(x):
    return math.cos(x)  # Test with cos(x)

x = 0.5  # Point to evaluate the derivative

# Test the function using different methods
for method in ['forward', 'backward', 'central']:
    derivative_value = derivative(test_function, x, method=method)
    print(f"Derivative using {method} method:", derivative_value)

Derivative using forward method: -0.483805424462147
Derivative using backward method: -0.4750296719748692
Derivative using central method: -0.4794175482185081


14. Download the Automatic Weather Station AWS Data. Read the .csv file using
pandas library as a DataFrame.

In [ ]:
import pandas as pd

file_path = r'D:\IITK docs\PROB & STAT CE605A\AWS.xlsx'  # Use 'r' before the string to treat it as a raw string

data_frame = pd.read_excel(file_path)

print(data_frame.head())
